name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: string
        description: 'Enter the Release type [major / minor / patch]'
        required: true
      releaseTicket:
        type: string
        description: 'Enter the Release ticket number'
        required: true

jobs:
  release:
    environment: publishing_gradle_config
    runs-on: ubuntu-latest
    steps:
      - name: Configure git
        shell: bash
        run: |
          git config --global user.name "sdk-bot-user"
          git config --global user.email "sdk.bot@moengage.com"
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19
      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Release
        env:
          publishKey: ${{ secrets.publishKey }}
          secretKey: ${{ secrets.secretKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
        run: |
          chmod +x ./.github/scripts/release.main.kts
          kotlinc -script ./.github/scripts/release.main.kts $publishKey $secretKey ${{ github.event.inputs.releaseType }} ${{ github.event.inputs.releaseTicket }}